### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JoseABCruz#2]

**Comment by JoseABCruz** [comment]
[Fases de la Gestión de proyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JoseABCruz/files/12444097/Fases.de.la.Gestion.de.proyectos.pdf)

**Comment by bg55-a** [comment]
calificacion:20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
